-- ============================================================================
--  設備類型管理：改名、排序、增刪（冰箱 / 空氣清新機 / 抽濕機 …）。
--  在 add_tools_equipment_fields.sql 之後跑一次。
-- ============================================================================
create table if not exists equipment_types (
  id         int generated by default as identity primary key,
  name       text not null unique,
  sort_order int  not null default 0
);
alter table equipment_types enable row level security;
drop policy if exists "public read equipment_types" on equipment_types;
create policy "public read equipment_types" on equipment_types for select using (true);

-- 從現有設備的類型帶入初始清單
insert into equipment_types (name, sort_order)
select name, row_number() over (order by name)
from (select distinct type as name from equipment where coalesce(type,'') <> '') s
on conflict (name) do nothing;
insert into equipment_types (name, sort_order) values ('其他', 999) on conflict (name) do nothing;

-- RPC：整批儲存（新增/改名/排序/刪除）；改名同步 equipment.type，刪除移到「其他」
create or replace function save_equipment_types(p_password text, p_cats jsonb)
returns void language plpgsql security definer set search_path = public, extensions as $$
declare
  el jsonb; i int := 0; cid int; nm text; oldnm text; keep int[] := '{}'; d record;
begin
  perform _require_admin(p_password);
  for el in select value from jsonb_array_elements(p_cats) loop
    i := i + 1;
    cid := nullif(el->>'id','')::int;
    nm := btrim(el->>'name');
    if nm is null or nm = '' then continue; end if;
    if cid is null then
      insert into equipment_types(name, sort_order) values (nm, i)
        on conflict (name) do update set sort_order = i
        returning id into cid;
    else
      select name into oldnm from equipment_types where id = cid;
      if oldnm is not null and oldnm <> nm then
        update equipment set type = nm where type = oldnm;
      end if;
      update equipment_types set name = nm, sort_order = i where id = cid;
    end if;
    keep := array_append(keep, cid);
  end loop;
  for d in select id, name from equipment_types where not (id = any(keep)) loop
    update equipment set type = '其他' where type = d.name;
    delete from equipment_types where id = d.id;
  end loop;
  insert into equipment_types(name, sort_order) values ('其他', 999) on conflict (name) do nothing;
end $$;
grant execute on function save_equipment_types(text, jsonb) to anon, authenticated;
