-- ============================================================================
--  酒店後勤系統 — 清潔劑「批次效期 + 用量統計」
--  在 schema.sql / seed.sql 之後執行（重用 _require_admin）。
--  模型：每個清潔劑 = 多個批次(product_batches)，總庫存 products.stock = 批次剩餘加總。
--        用量以「盤點推算」記錄：盤點時 (原總數 − 實數) = 用量，FEFO 從最早到期批次扣。
--        流水帳 stock_movements 記 in(進貨)/out(用量)/adjust(調整)/dispose(丟棄)。
-- ============================================================================

create table if not exists product_batches (
  id            int generated by default as identity primary key,
  product_id    int not null references products(id) on delete cascade,
  received_date date,                         -- 進貨日
  expiry_date   date,                         -- 到期日 (null = 未設)
  qty_received  int not null default 0,       -- 進貨數量
  qty_remaining int not null default 0,       -- 剩餘數量
  note          text,
  created_at    timestamptz not null default now()
);
create index if not exists product_batches_pid_idx on product_batches(product_id);
create index if not exists product_batches_expiry_idx on product_batches(product_id, expiry_date);

create table if not exists stock_movements (
  id          int generated by default as identity primary key,
  product_id  int not null references products(id) on delete cascade,
  kind        text not null,                  -- in | out | adjust | dispose
  qty         int not null,                   -- 一律正數；意義由 kind 決定
  happened_on date not null default current_date,
  note        text,
  created_at  timestamptz not null default now()
);
create index if not exists stock_movements_pid_idx on stock_movements(product_id);
create index if not exists stock_movements_date_idx on stock_movements(happened_on);

-- ---------------------------------------------------------------------------
--  RLS：只允許 anon 讀取
-- ---------------------------------------------------------------------------
alter table product_batches enable row level security;
alter table stock_movements enable row level security;

drop policy if exists "public read product_batches" on product_batches;
create policy "public read product_batches" on product_batches for select using (true);

drop policy if exists "public read stock_movements" on stock_movements;
create policy "public read stock_movements" on stock_movements for select using (true);

-- ---------------------------------------------------------------------------
--  helper：把 products.stock 同步成該產品所有批次剩餘量的加總
-- ---------------------------------------------------------------------------
create or replace function _sync_product_stock(p_product_id int) returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  update products
     set stock = coalesce((select sum(qty_remaining) from product_batches where product_id = p_product_id), 0)
   where id = p_product_id;
end $$;

-- ---------------------------------------------------------------------------
--  進貨：新增一個批次
-- ---------------------------------------------------------------------------
create or replace function receive_batch(p_password text, p_product_id int, p_qty int, p_expiry date, p_received date, p_note text)
returns products
language plpgsql security definer set search_path = public, extensions
as $$
declare prod products;
begin
  perform _require_admin(p_password);
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be positive'; end if;
  insert into product_batches (product_id, received_date, expiry_date, qty_received, qty_remaining, note)
  values (p_product_id, coalesce(p_received, current_date), p_expiry, p_qty, p_qty, p_note);
  insert into stock_movements (product_id, kind, qty, happened_on, note)
  values (p_product_id, 'in', p_qty, coalesce(p_received, current_date), p_note);
  perform _sync_product_stock(p_product_id);
  select * into prod from products where id = p_product_id;
  return prod;
end $$;

-- ---------------------------------------------------------------------------
--  盤點：填實際剩餘總數，系統推算用量並 FEFO 扣批次
-- ---------------------------------------------------------------------------
create or replace function stock_count(p_password text, p_product_id int, p_actual int, p_date date, p_note text)
returns products
language plpgsql security definer set search_path = public, extensions
as $$
declare
  prod products;
  cur int;
  diff int;
  need int;
  take int;
  addq int;
  latest int;
  b record;
  cdate date := coalesce(p_date, current_date);
begin
  perform _require_admin(p_password);
  if p_actual is null or p_actual < 0 then raise exception 'invalid count'; end if;
  select coalesce(sum(qty_remaining), 0) into cur from product_batches where product_id = p_product_id;
  diff := cur - p_actual;                       -- 正 = 用掉

  if diff > 0 then
    need := diff;
    for b in select id, qty_remaining from product_batches
             where product_id = p_product_id and qty_remaining > 0
             order by expiry_date asc nulls last, received_date asc, id asc
    loop
      exit when need <= 0;
      take := least(need, b.qty_remaining);
      update product_batches set qty_remaining = qty_remaining - take where id = b.id;
      need := need - take;
    end loop;
    insert into stock_movements (product_id, kind, qty, happened_on, note)
    values (p_product_id, 'out', diff, cdate, coalesce(p_note, '盤點'));

  elsif diff < 0 then
    addq := -diff;                              -- 實數 > 帳面：正向調整
    select id into latest from product_batches
      where product_id = p_product_id
      order by received_date desc nulls last, id desc limit 1;
    if latest is null then
      insert into product_batches (product_id, received_date, expiry_date, qty_received, qty_remaining, note)
      values (p_product_id, cdate, null, addq, addq, '盤點調整');
    else
      update product_batches set qty_remaining = qty_remaining + addq where id = latest;
    end if;
    insert into stock_movements (product_id, kind, qty, happened_on, note)
    values (p_product_id, 'adjust', addq, cdate, coalesce(p_note, '盤點調整(增加)'));
  end if;

  perform _sync_product_stock(p_product_id);
  select * into prod from products where id = p_product_id;
  return prod;
end $$;

-- ---------------------------------------------------------------------------
--  編輯批次（更正剩餘量 / 到期日 / 進貨日）— 視為更正，不計入用量
-- ---------------------------------------------------------------------------
create or replace function update_batch(p_password text, p_batch_id int, p_qty_remaining int, p_expiry date, p_received date, p_note text)
returns products
language plpgsql security definer set search_path = public, extensions
as $$
declare prod products; pid int;
begin
  perform _require_admin(p_password);
  select product_id into pid from product_batches where id = p_batch_id;
  if not found then raise exception 'batch not found'; end if;
  update product_batches set
    qty_remaining = coalesce(p_qty_remaining, qty_remaining),
    expiry_date   = p_expiry,
    received_date = coalesce(p_received, received_date),
    note          = p_note
  where id = p_batch_id;
  perform _sync_product_stock(pid);
  select * into prod from products where id = pid;
  return prod;
end $$;

-- ---------------------------------------------------------------------------
--  刪除批次（丟棄/過期）— 記 dispose，不計入用量
-- ---------------------------------------------------------------------------
create or replace function delete_batch(p_password text, p_batch_id int)
returns products
language plpgsql security definer set search_path = public, extensions
as $$
declare prod products; pid int; q int;
begin
  perform _require_admin(p_password);
  select product_id, qty_remaining into pid, q from product_batches where id = p_batch_id;
  if not found then raise exception 'batch not found'; end if;
  if q > 0 then
    insert into stock_movements (product_id, kind, qty, happened_on, note)
    values (pid, 'dispose', q, current_date, '刪除批次');
  end if;
  delete from product_batches where id = p_batch_id;
  perform _sync_product_stock(pid);
  select * into prod from products where id = pid;
  return prod;
end $$;

-- ---------------------------------------------------------------------------
--  Grants
-- ---------------------------------------------------------------------------
revoke all on function _sync_product_stock(int) from public, anon, authenticated;
grant execute on function receive_batch(text, int, int, date, date, text) to anon, authenticated;
grant execute on function stock_count(text, int, int, date, text)         to anon, authenticated;
grant execute on function update_batch(text, int, int, date, date, text)  to anon, authenticated;
grant execute on function delete_batch(text, int)                         to anon, authenticated;

-- ---------------------------------------------------------------------------
--  初始化：把現有庫存轉成「初始批次(未設效期)」，不遺失現有數字
-- ---------------------------------------------------------------------------
insert into product_batches (product_id, received_date, expiry_date, qty_received, qty_remaining, note)
select id, current_date, null, stock, stock, '初始庫存(未設效期)'
from products p
where p.stock > 0
  and not exists (select 1 from product_batches b where b.product_id = p.id);
