-- ============================================================================
--  酒店後勤系統 — 模組 4：設備（保險箱 / 空氣淨化機 / 除濕機 等）
--  每台獨立管理 + 保養記錄，按「類型」分組。
--  在 schema.sql 之後執行（重用 _require_admin / set_updated_at）。
-- ============================================================================

create table if not exists equipment (
  id          int generated by default as identity primary key,
  type        text not null default '其他',   -- 保險箱 / 空氣淨化機 / 除濕機 / ...
  model       text,                            -- 型號
  brand       text,                            -- 品牌
  floor_code  text,                            -- 樓層代號
  status      text not null default '正常',    -- 正常 | 維修中 | 報廢
  image       text,
  notes       text,
  sort_order  int  not null default 0,
  updated_at  timestamptz not null default now()
);

create table if not exists equipment_maintenance (
  id            int generated by default as identity primary key,
  equipment_id  int not null references equipment(id) on delete cascade,
  service_date  date not null default current_date,
  description   text not null,
  created_at    timestamptz not null default now()
);
create index if not exists equipment_maintenance_eid_idx on equipment_maintenance(equipment_id);

drop trigger if exists equipment_updated_at on equipment;
create trigger equipment_updated_at before update on equipment
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
--  RLS：只允許 anon 讀取
-- ---------------------------------------------------------------------------
alter table equipment             enable row level security;
alter table equipment_maintenance enable row level security;

drop policy if exists "public read equipment" on equipment;
create policy "public read equipment" on equipment for select using (true);

drop policy if exists "public read equipment_maintenance" on equipment_maintenance;
create policy "public read equipment_maintenance" on equipment_maintenance for select using (true);

-- ---------------------------------------------------------------------------
--  RPC
-- ---------------------------------------------------------------------------
create or replace function upsert_equipment(p_password text, p_equipment jsonb)
returns equipment
language plpgsql security definer set search_path = public, extensions
as $$
declare
  rec equipment;
  eid int := nullif(p_equipment->>'id','')::int;
begin
  perform _require_admin(p_password);
  if eid is null then
    insert into equipment (type, model, brand, floor_code, status, image, notes, sort_order)
    values (
      coalesce(nullif(p_equipment->>'type',''), '其他'),
      p_equipment->>'model', p_equipment->>'brand', p_equipment->>'floor_code',
      coalesce(nullif(p_equipment->>'status',''), '正常'),
      p_equipment->>'image', p_equipment->>'notes',
      coalesce(nullif(p_equipment->>'sort_order','')::int, 0)
    ) returning * into rec;
  else
    update equipment set
      type       = coalesce(nullif(p_equipment->>'type',''), type),
      model      = p_equipment->>'model',
      brand      = p_equipment->>'brand',
      floor_code = p_equipment->>'floor_code',
      status     = coalesce(nullif(p_equipment->>'status',''), status),
      image      = coalesce(p_equipment->>'image', image),
      notes      = p_equipment->>'notes',
      sort_order = coalesce(nullif(p_equipment->>'sort_order','')::int, sort_order)
    where id = eid returning * into rec;
    if not found then raise exception 'equipment not found'; end if;
  end if;
  return rec;
end $$;

create or replace function update_equipment_status(p_password text, p_id int, p_status text)
returns equipment
language plpgsql security definer set search_path = public, extensions
as $$
declare rec equipment;
begin
  perform _require_admin(p_password);
  if p_status not in ('正常', '維修中', '報廢') then raise exception 'invalid status'; end if;
  update equipment set status = p_status where id = p_id returning * into rec;
  if not found then raise exception 'equipment not found'; end if;
  return rec;
end $$;

create or replace function delete_equipment(p_password text, p_id int)
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from equipment where id = p_id;
end $$;

create or replace function add_equipment_maintenance(p_password text, p_equipment_id int, p_date date, p_description text)
returns equipment_maintenance
language plpgsql security definer set search_path = public, extensions
as $$
declare rec equipment_maintenance;
begin
  perform _require_admin(p_password);
  if coalesce(trim(p_description),'') = '' then raise exception 'description required'; end if;
  insert into equipment_maintenance (equipment_id, service_date, description)
  values (p_equipment_id, coalesce(p_date, current_date), p_description)
  returning * into rec;
  return rec;
end $$;

create or replace function delete_equipment_maintenance(p_password text, p_id int)
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from equipment_maintenance where id = p_id;
end $$;

-- ---------------------------------------------------------------------------
--  Grants
-- ---------------------------------------------------------------------------
grant execute on function upsert_equipment(text, jsonb)                    to anon, authenticated;
grant execute on function update_equipment_status(text, int, text)         to anon, authenticated;
grant execute on function delete_equipment(text, int)                      to anon, authenticated;
grant execute on function add_equipment_maintenance(text, int, date, text) to anon, authenticated;
grant execute on function delete_equipment_maintenance(text, int)          to anon, authenticated;
