-- ============================================================================
--  酒店後勤系統 — 模組 2 (吸塵機) + 模組 3 (清潔工具)
--  在 schema.sql 之後執行（重用 _require_admin / verify_password / pgcrypto）。
-- ============================================================================

-- ---------------------------------------------------------------------------
--  模組 2：吸塵機（每台獨立管理 + 保養記錄）
-- ---------------------------------------------------------------------------
create table if not exists vacuums (
  id          int generated by default as identity primary key,
  model       text not null,          -- 型號
  brand       text,                   -- 品牌
  floor_code  text,                   -- 樓層代號
  status      text not null default '正常',   -- 正常 | 維修中 | 報廢
  image       text,                   -- data:image/...;base64,...  或 URL
  notes       text,
  sort_order  int  not null default 0,
  updated_at  timestamptz not null default now()
);

create table if not exists vacuum_maintenance (
  id           int generated by default as identity primary key,
  vacuum_id    int not null references vacuums(id) on delete cascade,
  service_date date not null default current_date,   -- 保養日期
  description  text not null,                          -- 做了什麼（換零件 / 清洗…）
  created_at   timestamptz not null default now()
);
create index if not exists vacuum_maintenance_vid_idx on vacuum_maintenance(vacuum_id);

drop trigger if exists vacuums_updated_at on vacuums;
create trigger vacuums_updated_at before update on vacuums
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
--  模組 3：清潔工具（庫存數量，做法同清潔劑）
-- ---------------------------------------------------------------------------
create table if not exists tools (
  id          int generated by default as identity primary key,
  name        text not null,
  stock       int  not null default 0,
  status      text not null default '啟用',   -- 啟用 | 停用
  image       text,
  notes       text,
  sort_order  int  not null default 0,
  updated_at  timestamptz not null default now()
);

drop trigger if exists tools_updated_at on tools;
create trigger tools_updated_at before update on tools
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
--  RLS：全部只允許 anon 讀取，寫入只能經由下面的 RPC
-- ---------------------------------------------------------------------------
alter table vacuums            enable row level security;
alter table vacuum_maintenance enable row level security;
alter table tools              enable row level security;

drop policy if exists "public read vacuums" on vacuums;
create policy "public read vacuums" on vacuums for select using (true);

drop policy if exists "public read vacuum_maintenance" on vacuum_maintenance;
create policy "public read vacuum_maintenance" on vacuum_maintenance for select using (true);

drop policy if exists "public read tools" on tools;
create policy "public read tools" on tools for select using (true);

-- ---------------------------------------------------------------------------
--  RPC — 吸塵機
-- ---------------------------------------------------------------------------
create or replace function upsert_vacuum(p_password text, p_vacuum jsonb)
returns vacuums
language plpgsql security definer set search_path = public, extensions
as $$
declare
  rec vacuums;
  vid int := nullif(p_vacuum->>'id','')::int;
begin
  perform _require_admin(p_password);
  if vid is null then
    insert into vacuums (model, brand, floor_code, status, image, notes, sort_order)
    values (
      p_vacuum->>'model', p_vacuum->>'brand', p_vacuum->>'floor_code',
      coalesce(nullif(p_vacuum->>'status',''), '正常'),
      p_vacuum->>'image', p_vacuum->>'notes',
      coalesce(nullif(p_vacuum->>'sort_order','')::int, 0)
    ) returning * into rec;
  else
    update vacuums set
      model      = coalesce(p_vacuum->>'model', model),
      brand      = p_vacuum->>'brand',
      floor_code = p_vacuum->>'floor_code',
      status     = coalesce(nullif(p_vacuum->>'status',''), status),
      image      = coalesce(p_vacuum->>'image', image),
      notes      = p_vacuum->>'notes',
      sort_order = coalesce(nullif(p_vacuum->>'sort_order','')::int, sort_order)
    where id = vid returning * into rec;
    if not found then raise exception 'vacuum not found'; end if;
  end if;
  return rec;
end $$;

create or replace function update_vacuum_status(p_password text, p_id int, p_status text)
returns vacuums
language plpgsql security definer set search_path = public, extensions
as $$
declare rec vacuums;
begin
  perform _require_admin(p_password);
  if p_status not in ('正常', '維修中', '報廢') then raise exception 'invalid status'; end if;
  update vacuums set status = p_status where id = p_id returning * into rec;
  if not found then raise exception 'vacuum not found'; end if;
  return rec;
end $$;

create or replace function delete_vacuum(p_password text, p_id int)
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from vacuums where id = p_id;   -- maintenance rows cascade
end $$;

create or replace function add_vacuum_maintenance(p_password text, p_vacuum_id int, p_date date, p_description text)
returns vacuum_maintenance
language plpgsql security definer set search_path = public, extensions
as $$
declare rec vacuum_maintenance;
begin
  perform _require_admin(p_password);
  if coalesce(trim(p_description),'') = '' then raise exception 'description required'; end if;
  insert into vacuum_maintenance (vacuum_id, service_date, description)
  values (p_vacuum_id, coalesce(p_date, current_date), p_description)
  returning * into rec;
  return rec;
end $$;

create or replace function delete_vacuum_maintenance(p_password text, p_id int)
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from vacuum_maintenance where id = p_id;
end $$;

-- ---------------------------------------------------------------------------
--  RPC — 清潔工具
-- ---------------------------------------------------------------------------
create or replace function upsert_tool(p_password text, p_tool jsonb)
returns tools
language plpgsql security definer set search_path = public, extensions
as $$
declare
  rec tools;
  tid int := nullif(p_tool->>'id','')::int;
begin
  perform _require_admin(p_password);
  if tid is null then
    insert into tools (name, stock, status, image, notes, sort_order)
    values (
      p_tool->>'name',
      coalesce(nullif(p_tool->>'stock','')::int, 0),
      coalesce(nullif(p_tool->>'status',''), '啟用'),
      p_tool->>'image', p_tool->>'notes',
      coalesce(nullif(p_tool->>'sort_order','')::int, 0)
    ) returning * into rec;
  else
    update tools set
      name       = coalesce(p_tool->>'name', name),
      stock      = coalesce(nullif(p_tool->>'stock','')::int, stock),
      status     = coalesce(nullif(p_tool->>'status',''), status),
      image      = coalesce(p_tool->>'image', image),
      notes      = p_tool->>'notes',
      sort_order = coalesce(nullif(p_tool->>'sort_order','')::int, sort_order)
    where id = tid returning * into rec;
    if not found then raise exception 'tool not found'; end if;
  end if;
  return rec;
end $$;

create or replace function update_tool_stock(p_password text, p_id int, p_stock int)
returns tools
language plpgsql security definer set search_path = public, extensions
as $$
declare rec tools;
begin
  perform _require_admin(p_password);
  if p_stock < 0 then p_stock := 0; end if;
  update tools set stock = p_stock where id = p_id returning * into rec;
  if not found then raise exception 'tool not found'; end if;
  return rec;
end $$;

create or replace function update_tool_status(p_password text, p_id int, p_status text)
returns tools
language plpgsql security definer set search_path = public, extensions
as $$
declare rec tools;
begin
  perform _require_admin(p_password);
  if p_status not in ('啟用', '停用') then raise exception 'invalid status'; end if;
  update tools set status = p_status where id = p_id returning * into rec;
  if not found then raise exception 'tool not found'; end if;
  return rec;
end $$;

create or replace function delete_tool(p_password text, p_id int)
returns void
language plpgsql security definer set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from tools where id = p_id;
end $$;

-- ---------------------------------------------------------------------------
--  Grants — anon 可執行（函式內部驗密碼）；直接寫表仍被 RLS 擋住
-- ---------------------------------------------------------------------------
grant execute on function upsert_vacuum(text, jsonb)               to anon, authenticated;
grant execute on function update_vacuum_status(text, int, text)    to anon, authenticated;
grant execute on function delete_vacuum(text, int)                 to anon, authenticated;
grant execute on function add_vacuum_maintenance(text, int, date, text) to anon, authenticated;
grant execute on function delete_vacuum_maintenance(text, int)     to anon, authenticated;
grant execute on function upsert_tool(text, jsonb)                 to anon, authenticated;
grant execute on function update_tool_stock(text, int, int)        to anon, authenticated;
grant execute on function update_tool_status(text, int, text)      to anon, authenticated;
grant execute on function delete_tool(text, int)                   to anon, authenticated;
