-- ============================================================================
--  MNT Cleaning Catalog — Supabase schema
--  Run this ONCE in the Supabase SQL Editor (Dashboard → SQL Editor → New query)
--  Order: 1) this file  2) seed.sql  3) set the admin password (bottom of file)
-- ============================================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
--  Tables
-- ---------------------------------------------------------------------------
create table if not exists categories (
  id         int primary key,
  icon       text,
  name_zh    text not null,
  name_en    text,
  color      text,            -- accent / border colour, e.g. #E74C3C
  bg         text,            -- header background, e.g. #FEF0EF
  sort_order int not null default 0
);

create table if not exists products (
  id            int generated by default as identity primary key,
  category_id   int references categories(id) on delete set null,
  name_zh       text not null,
  name_en       text,
  subname_zh    text,
  subname_en    text,
  applicable_zh text,
  applicable_en text,
  dilution_zh   text,
  dilution_en   text,
  rinse_zh      text,          -- 需要 / 不需要
  rinse_en      text,          -- Required / Not required
  image         text,          -- data:image/...;base64,....  (or a URL)
  alt           text,
  stock         int  not null default 0,
  status        text not null default '啟用',   -- 啟用 | 停用
  sort_order    int  not null default 0,
  updated_at    timestamptz not null default now()
);

create index if not exists products_category_idx on products(category_id);

-- keep updated_at fresh
create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists products_updated_at on products;
create trigger products_updated_at before update on products
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
--  Admin password (single shared password, stored as a bcrypt hash)
-- ---------------------------------------------------------------------------
create table if not exists app_config (
  key   text primary key,
  value text not null
);

-- ---------------------------------------------------------------------------
--  Row Level Security
--  - categories / products : anyone (anon) may READ. No direct write policy,
--    so INSERT/UPDATE/DELETE through the public anon key are impossible.
--  - app_config            : RLS on, NO policies -> the password hash is
--    unreadable to the anon key. Only SECURITY DEFINER functions can touch it.
-- ---------------------------------------------------------------------------
alter table categories enable row level security;
alter table products   enable row level security;
alter table app_config enable row level security;

drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories
  for select using (true);

drop policy if exists "public read products" on products;
create policy "public read products" on products
  for select using (true);

-- (no policies on app_config on purpose)

-- ---------------------------------------------------------------------------
--  Password helpers
-- ---------------------------------------------------------------------------

-- Internal: raise if the supplied password does not match the stored hash.
create or replace function _require_admin(p_password text) returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare stored text;
begin
  select value into stored from app_config where key = 'admin_password_hash';
  if stored is null then
    raise exception 'admin password not configured';
  end if;
  if p_password is null or crypt(p_password, stored) <> stored then
    raise exception 'wrong password' using errcode = '28000';
  end if;
end $$;

-- Public: verify a password (used by the login modal). Returns true/false.
create or replace function verify_password(p_password text) returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare stored text;
begin
  select value into stored from app_config where key = 'admin_password_hash';
  if stored is null then return false; end if;
  return crypt(p_password, stored) = stored;
end $$;

-- ---------------------------------------------------------------------------
--  Admin write RPCs (password-gated, run as owner via SECURITY DEFINER)
-- ---------------------------------------------------------------------------

create or replace function update_stock(p_password text, p_id int, p_stock int)
returns products
language plpgsql
security definer
set search_path = public, extensions
as $$
declare rec products;
begin
  perform _require_admin(p_password);
  if p_stock < 0 then p_stock := 0; end if;
  update products set stock = p_stock where id = p_id returning * into rec;
  if not found then raise exception 'product not found'; end if;
  return rec;
end $$;

create or replace function update_status(p_password text, p_id int, p_status text)
returns products
language plpgsql
security definer
set search_path = public, extensions
as $$
declare rec products;
begin
  perform _require_admin(p_password);
  if p_status not in ('啟用', '停用') then
    raise exception 'invalid status';
  end if;
  update products set status = p_status where id = p_id returning * into rec;
  if not found then raise exception 'product not found'; end if;
  return rec;
end $$;

-- Add or edit a product. Pass the whole product as jsonb.
-- If p_product->>'id' is null/absent an INSERT happens, otherwise an UPDATE.
create or replace function upsert_product(p_password text, p_product jsonb)
returns products
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  rec products;
  pid int := nullif(p_product->>'id','')::int;
begin
  perform _require_admin(p_password);

  if pid is null then
    insert into products (
      category_id, name_zh, name_en, subname_zh, subname_en,
      applicable_zh, applicable_en, dilution_zh, dilution_en,
      rinse_zh, rinse_en, image, alt, stock, status, sort_order
    ) values (
      nullif(p_product->>'category_id','')::int,
      p_product->>'name_zh', p_product->>'name_en',
      p_product->>'subname_zh', p_product->>'subname_en',
      p_product->>'applicable_zh', p_product->>'applicable_en',
      p_product->>'dilution_zh', p_product->>'dilution_en',
      p_product->>'rinse_zh', p_product->>'rinse_en',
      p_product->>'image', p_product->>'alt',
      coalesce(nullif(p_product->>'stock','')::int, 0),
      coalesce(nullif(p_product->>'status',''), '啟用'),
      coalesce(nullif(p_product->>'sort_order','')::int, 0)
    ) returning * into rec;
  else
    update products set
      category_id   = nullif(p_product->>'category_id','')::int,
      name_zh       = coalesce(p_product->>'name_zh', name_zh),
      name_en       = p_product->>'name_en',
      subname_zh    = p_product->>'subname_zh',
      subname_en    = p_product->>'subname_en',
      applicable_zh = p_product->>'applicable_zh',
      applicable_en = p_product->>'applicable_en',
      dilution_zh   = p_product->>'dilution_zh',
      dilution_en   = p_product->>'dilution_en',
      rinse_zh      = p_product->>'rinse_zh',
      rinse_en      = p_product->>'rinse_en',
      image         = coalesce(p_product->>'image', image),
      alt           = p_product->>'alt',
      stock         = coalesce(nullif(p_product->>'stock','')::int, stock),
      status        = coalesce(nullif(p_product->>'status',''), status),
      sort_order    = coalesce(nullif(p_product->>'sort_order','')::int, sort_order)
    where id = pid returning * into rec;
    if not found then raise exception 'product not found'; end if;
  end if;
  return rec;
end $$;

create or replace function delete_product(p_password text, p_id int)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  perform _require_admin(p_password);
  delete from products where id = p_id;
end $$;

-- ---------------------------------------------------------------------------
--  Grants — the public anon key may EXECUTE these functions; the functions
--  themselves enforce the password. Direct table writes stay blocked by RLS.
-- ---------------------------------------------------------------------------
revoke all on function _require_admin(text) from public, anon, authenticated;

grant execute on function verify_password(text)            to anon, authenticated;
grant execute on function update_stock(text, int, int)     to anon, authenticated;
grant execute on function update_status(text, int, text)   to anon, authenticated;
grant execute on function upsert_product(text, jsonb)      to anon, authenticated;
grant execute on function delete_product(text, int)        to anon, authenticated;

-- ---------------------------------------------------------------------------
--  SET THE ADMIN PASSWORD  ▸ replace 'CHANGE_ME_NOW' and run this line.
--  (Run again anytime to change the password.)
-- ---------------------------------------------------------------------------
insert into app_config (key, value)
values ('admin_password_hash', crypt('CHANGE_ME_NOW', gen_salt('bf')))
on conflict (key) do update set value = excluded.value;
