-- ============================================================================
--  清潔工具分類管理：可改名、排序、增刪。
--  在 add_tools_equipment_fields.sql 之後跑一次。
-- ============================================================================
create table if not exists tool_categories (
  id         int generated by default as identity primary key,
  name       text not null unique,
  sort_order int  not null default 0
);
alter table tool_categories enable row level security;
drop policy if exists "public read tool_categories" on tool_categories;
create policy "public read tool_categories" on tool_categories for select using (true);

-- 初始分類（把「洗手液」改成「洗手液器」）
insert into tool_categories (name, sort_order) values
  ('垃圾桶', 1), ('防滑牌', 2), ('洗手液器', 3), ('其他', 99)
on conflict (name) do nothing;

-- 現有工具若還是舊名「洗手液」，一併更名
update tools set category = '洗手液器' where category = '洗手液';

-- ---------------------------------------------------------------------------
--  RPC：整批儲存分類清單（新增/改名/排序/刪除）；改名時同步更新 tools，
--       刪除時把該分類的工具移到「其他」。前端送出完整想要的清單。
-- ---------------------------------------------------------------------------
create or replace function save_tool_categories(p_password text, p_cats jsonb)
returns void language plpgsql security definer set search_path = public, extensions as $$
declare
  el jsonb; i int := 0; cid int; nm text; oldnm text; keep int[] := '{}';
  d record;
begin
  perform _require_admin(p_password);
  for el in select value from jsonb_array_elements(p_cats) loop
    i := i + 1;
    cid := nullif(el->>'id','')::int;
    nm := btrim(el->>'name');
    if nm is null or nm = '' then continue; end if;
    if cid is null then
      insert into tool_categories(name, sort_order) values (nm, i)
        on conflict (name) do update set sort_order = i
        returning id into cid;
    else
      select name into oldnm from tool_categories where id = cid;
      if oldnm is not null and oldnm <> nm then
        update tools set category = nm where category = oldnm;
      end if;
      update tool_categories set name = nm, sort_order = i where id = cid;
    end if;
    keep := array_append(keep, cid);
  end loop;
  for d in select id, name from tool_categories where not (id = any(keep)) loop
    update tools set category = '其他' where category = d.name;
    delete from tool_categories where id = d.id;
  end loop;
  insert into tool_categories(name, sort_order) values ('其他', 999) on conflict (name) do nothing;
end $$;
grant execute on function save_tool_categories(text, jsonb) to anon, authenticated;
