-- ============================================================================
--  吸塵機「樓層/區域」管理：改名、排序、增刪。
--  改名同步 vacuums.floor_code；刪除時把該樓層的機器改為未指定(null)。
--  在 import_data.sql 之後跑一次。
-- ============================================================================
create table if not exists vacuum_floors (
  id         int generated by default as identity primary key,
  name       text not null unique,
  sort_order int  not null default 0
);
alter table vacuum_floors enable row level security;
drop policy if exists "public read vacuum_floors" on vacuum_floors;
create policy "public read vacuum_floors" on vacuum_floors for select using (true);

-- 從現有機器的位置帶入初始清單
insert into vacuum_floors (name, sort_order)
select name, row_number() over (order by name)
from (select distinct btrim(floor_code) as name from vacuums where coalesce(btrim(floor_code),'') <> '') s
on conflict (name) do nothing;

create or replace function save_vacuum_floors(p_password text, p_cats jsonb)
returns void language plpgsql security definer set search_path = public, extensions as $$
declare
  el jsonb; i int := 0; cid int; nm text; oldnm text; keep int[] := '{}'; d record;
begin
  perform _require_admin(p_password);
  for el in select value from jsonb_array_elements(p_cats) loop
    i := i + 1;
    cid := nullif(el->>'id','')::int;
    nm := btrim(el->>'name');
    if nm is null or nm = '' then continue; end if;
    if cid is null then
      insert into vacuum_floors(name, sort_order) values (nm, i)
        on conflict (name) do update set sort_order = i
        returning id into cid;
    else
      select name into oldnm from vacuum_floors where id = cid;
      if oldnm is not null and oldnm <> nm then
        update vacuums set floor_code = nm where floor_code = oldnm;
      end if;
      update vacuum_floors set name = nm, sort_order = i where id = cid;
    end if;
    keep := array_append(keep, cid);
  end loop;
  for d in select id, name from vacuum_floors where not (id = any(keep)) loop
    update vacuums set floor_code = null where floor_code = d.name;
    delete from vacuum_floors where id = d.id;
  end loop;
end $$;
grant execute on function save_vacuum_floors(text, jsonb) to anon, authenticated;
